apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kwet-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kwet-service
  minReplicas: 2
  maxReplicas: 12
  targetCPUUtilizationPercentage: 75